#!/bin/sh

cvr () {
  browserify -t coverify test/**.js | testling | coverify
}

tst () {
  testling
}

mktst () {
  testling --html > test.html
  bloodyserver
}

nid () {
  npm install $1 --save-dev
}

ni () {
  npm install $1 --save
}
