#!/bin/sh

mkd () {
  mkdir -p "$@" && "$@"
}

# from https://github.com/mathiasbynens/dotfiles/blob/master/.functions#L79-L86
dataurl () {
  local mimeType=$(file -b --mime-type "$1")
  if [[ $mimeType == text/* ]]; then
    mimeType="${mimeType};charset=utf-8"
  fi
  echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
}
